### ISSUE TITLE
Canonical First?

### ISSUE THREAD

**Issue by nick-harper** [mattwright/URLResolver.php#5]
Hi,

Is it possible to get the Canonical URL as a priority? I have found in some cases the og:link has things like ?ref=facebook at the end which I don't want whereas the canonical is the normal link.

**Comment by bjm1** [comment]
I changed the order of the above statements, but it did not return the canonical URL as expected.

For example, in this link there is an og:url and a canonical link, but they are different. Expected result is to only return the canonical link. 

Resolve this link:
http://www.goodgearguide.com.au/article/607565/forza-horizon-3-review-best-arcade-racing-series-around-roars-onto-pcs/

og:url is same is above

Canonical link is:
http://www.pcworld.com/article/3124011/software/forza-horizon-3-review-the-best-arcade-racing-series-around-roars-onto-pcs.html

Options:
1) Can og:url detection be disabled?
2) Can canonical link have priority?

**Comment by mattwright** [comment]
Probably too late for you to care, but I have added $resolver->setPreferCanonicalURL(true) to the library so you can prefer the canonical link over the og:url link if you prefer. Available in v2.0
